- name: creating backend
  hosts: backend
  become: yes
  tasks:
  - name: installing node js
    ansible.builtin.command: dnf module enable nodejs:20 -y
    ansible.builtin.command: dnf install nodejs -y
    register: nodejs_output
  - name: print output of nodejs_output
    debug:
      msg: "{{ nodejs_output }}"
    when: nodejs_output.rc == 0
  - name: status of nodejs
    debug: 
      msg: "node js installed success"
    
     