- name: create ec2 instance and R53 
  hosts: all
  connection: local
  vars:
   instances:
   - backend
   - frontend
   - mysql
   env: Dev
   action: create

  tasks:
    - name: create EC2
      amazon.aws.ec2_instance:
        instance_type: "t3.micro"
        security_group: "sg-038949a8e5b397184"
        image_id: "ami-0220d79f3f480ecf5"
        name: "{{ item }}-{{ env }}"
        tags:
          Environment: development
          Project: Expense
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: ec2 out print
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"


    - name: delete ec2 instance
      amazon.aws.ec2_instance:
       state: absent
       name: "{{ item }}-{{ env }}"
       wait: false
      loop: "{{ instances }}"
      when: action == "destroy"