- name: create ec2 instance and R53 
  hosts: all
  connection: local
  vars:
   instances:
   - backend
   - frontend
   - mysql
   env: Dev
   action: create
   DOMAIN_NAME: narayanareddy.online

  tasks:
    - name: create EC2
      amazon.aws.ec2_instance:
        instance_type: "t3.micro"
        security_group: "sg-038949a8e5b397184"
        image_id: "ami-0220d79f3f480ecf5"
        name: "{{ item }}-{{ env }}"
        tags:
          Environment: development
          Project: Expense
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: ec2 out print
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"

    - name: create R53 records
      amazon.aws.route53:
        state: present
        zone: "{{ DOMAIN_NAME }}"
        record: "{{ item.item }}-{{ env }}.{{ DOMAIN_NAME }}"  #backend-dev.narayanareddy.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
      loop: "{{ ec2_output.results }}"
    - name: create r53 record for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ DOMAIN_NAME }}"
        record: "expense-{{ env }}.{{ DOMAIN_NAME }}" # roboshop-dev.daws88s.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: false
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when:  # and
      - item.item == "frontend"
      - action == "create"
          
    - name: delete ec2 instance
      amazon.aws.ec2_instance:
       state: absent
       name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      when: action == "destroy"